apiVersion: v1
kind: Config
clusters:
  - name: gewis-prod
    cluster:
      server: https://gewis-prod.netbird-kubeapi-proxy.net.nb.gewis.nl
      insecure-skip-tls-verify: true
users:
  - name: mesh
    user:
      token: unused-proxy-authenticates-by-netbird-mesh-identity
contexts:
  - name: gewis-prod
    context:
      cluster: gewis-prod
      user: mesh
current-context: gewis-prod
