apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: postgres
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17

  inheritedMetadata:
    labels:
      recurring-job.longhorn.io/all: "disabled"

  storage:
    size: 20Gi

  backup:
    volumeSnapshot:
      className: longhorn-backup-vsc
