---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAICoeJdnEMxPtMbc+jGXjgnS5IiRO7ExVE0P0P3wbHWWovD5CSsZonCq+6QbGP9ubElM7kpvV4ZIJ9Q+uDXfRTtMAQqdbfYLPgSrJ5VTNfAWa/Wk1fWoKvE8uPaCkvvyUY/t/QztlpTX4RSGy2RIXmtQge/FjQcK5wkicfgofoBZmWOgl4zd/cUH+Kj7HHHQJJXqyRbjlYP65ejTWB7g9MrRVkgiC5cQw/cneLT9HKy/u4Q7/l7nsPuE14i0JIJKaA399xdaO0RyuHoq6fudfdvXQVIaS/a+8PChvAzztRyeaHbIABCwgQJnjLOIsecl4Z/SOhITDQqh76p8m4xZ2IvNUu91EC2aXoywsmabJbX8CSXsnd40DoDBeiegxKjkqY3QhWLZcVJCipnk7JM7U4PQmfD1sZycFw21YjDYBgHm/oePdkYw6xKxAmk/lXsiIKvdL24hMl88lwxrgh1aGFvat0rmuWSTm9WtU5+q1QUCFgoPW53pfvEzQf66BEUGnbDcVyUQnzGx0ST0O58SpSM+jLhRbvy5EckWjjunozDUduMhKe0Xx2Kp4+LHXd+mVdGQtz/5JT0Ts+c08bgzFpOtGfZPIoceY/FdPYvBD8ziYQ/c4LQfOQJP4jTqNm67TdQ0UR+8aEgkolu6Rngtdeh/3m0794B/3nv+kj4h+JL5bDqyVFpYNN8pkjY6DpPD3aWanlosTGLNeChgT8+LqbUyd/HkHLXmvri8f9O1o8R1eTFADPMU0T
  template:
    metadata:
      name: cloudflare
      namespace: cert-manager
    type: Opaque
