apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coredns
  namespace: flux-system
spec:
  targetNamespace: coredns
  storageNamespace: coredns
  chart:
    spec:
      chart: coredns
      version: "1.46.0"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: coredns
        namespace: flux-system
  interval: 1h
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    isClusterService: false
    serviceType: LoadBalancer
    servers:
    - zones:
      - zone: .
        use_tcp: true
      port: 53
      plugins:
      - name: errors
      - name: health
        configBlock: |-
          lameduck 10s
      - name: ready
      - name: forward
        parameters: . 131.155.3.3 131.155.2.3
        configBlock: |-
          policy sequential
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance
