apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coredns
  namespace: flux-system
spec:
  targetNamespace: coredns
  storageNamespace: coredns
  chart:
    spec:
      chart: coredns
      version: "1.46.0"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: coredns
        namespace: flux-system
  interval: 1h
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    isClusterService: false
    replicaCount: 3
    serviceType: LoadBalancer
    image:
      # Use the image provided by K3s
      repository: "docker.io/rancher/mirrored-coredns-coredns"
      tag: "1.14.7"
    servers:
    - zones:
      - zone: .
        use_tcp: true
      port: 53
      plugins:
      - name: errors
      - name: health
        configBlock: |-
          lameduck 10s
      - name: ready
      - name: forward
        parameters: gewiswg.gewis.nl 10.82.40.22 10.82.40.23
        configBlock: |-
          policy sequential
      - name: forward
        parameters: . 131.155.2.3 131.155.3.3
        configBlock: |-
          policy sequential
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance
---
# add a second interface to get a second LB IP as many
# devices expect at least two DNS servers
apiVersion: v1
kind: Service
metadata:
  name: coredns-coredns-2
  namespace: coredns
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: coredns-coredns
    app.kubernetes.io/name: coredns
  ports:
  - name: udp-53
    port: 53
    protocol: UDP
  - name: tcp-53
    port: 53
    protocol: TCP