apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: db-provider
spec:
  credentials:
    source: PostgreSQLConnectionURI
    connectionSecretRef:
      namespace: postgres
      name: postgres-superuser
