apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpostgresdatabases.databases.gewis.nl
spec:
  group: databases.gewis.nl
  names:
    kind: XPostgresDatabase
    plural: xpostgresdatabases
  claimNames:
    kind: PostgresDatabase
    plural: postgresdatabases
  connectionSecretKeys:
    - host
    - port
    - database
    - username
    - password
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    databaseName:
                      type: string
                      description: |
                        Name of the PostgreSQL database and role to create.
                        Defaults to the claim name if not set.
