apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-loki
  namespace: observability
  labels:
    grafana_datasource: "1"
data:
  loki-multitenant.yaml: |-
    apiVersion: 1
    datasources:
      # Organization: CBC
      - name: Loki
        type: loki
        orgId: 1
        url: http://loki-gateway.observability.svc.cluster.local
        editable: false
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "CBC"

      # Organization: ABC - CRM
      - name: Loki
        type: loki
        orgId: 2
        url: http://loki-gateway.observability.svc.cluster.local
        editable: false
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "ABC-CRM"

      # Organization: ABC - EOU
      - name: Loki
        type: loki
        orgId: 3
        url: http://loki-gateway.observability.svc.cluster.local
        editable: false
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "ABC-EOU"

      # Organization: ABC - DB
      - name: Loki
        type: loki
        orgId: 4
        url: http://loki-gateway.observability.svc.cluster.local
        editable: false
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "ABC-DB"

      # Organization: ABC - WEB
      - name: Loki
        type: loki
        orgId: 5
        url: http://loki-gateway.observability.svc.cluster.local
        editable: false
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "ABC-WEB"

      # Organization: ABC - NC
      - name: Loki
        type: loki
        orgId: 6
        url: http://loki-gateway.observability.svc.cluster.local
        editable: false
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "ABC-NC"

      # Organization: ABC - POS
      - name: Loki
        type: loki
        orgId: 7
        url: http://loki-gateway.observability.svc.cluster.local
        editable: false
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "ABC-POS"
