---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc-auth
  namespace: shared-secrets
spec:
  encryptedData:
    pluginSecret: AgDBce5B7b/oN36+sxhyhRLgfiKg4uyJIQIQH+L833aGn9vVEHAd3xor8GPZl5+CAJKtWZvm05amJ4Zd0NOG67pvQEgQ+skeDI1HGLX6AFqGmhkWAWmPovIPYHYRL/mxyDDUcvO6Q5rr1vMPHFHN/8wyTLwGMlxrSwXpTewjO7wq0cnSMEd+xCTg2y/kxUeMAZhAwAm2Dldh7fxxNlXiotNHhjDAWo0/whcegKu/mE+yfPfrV+OtI5/5Y4/RSd/VgPp7YFJuw6kXGp246N+hjgx83sPAZHwcmE5uh3ym0rizG9z0hH/fcH/Gb+ldcyX22Qc/OfuI1MEH421Fjnjv2RE64sUGVvKfyaxj9WPVmYPIH0+N+Cnti4xb5E8j/1uDNKc1RqJJMZGmjgLeSyVcBh5phJmMNnocyarbSUKUCuQKpgvuqQ/umqNAUdWztHZZ0A4lhe+P8vuxjVKJisU2t63jx13tX7ENxa82PMU1CJZMfRwQxAJ1uUPsH1T63hfZ5tcCye0D3O/6S3cnUVlanhxlUk9FV+woEFgv3j6bP8GpbHRuwpxOPLWSeNXwTTE6f2c3zxhdMYaNu8RT07XZrcatycpJTxfNJ+3oJuDuJjGZoue08I3c17vC+kiOG5uGW3bRvlkdsNj1QNVeEtHbtMvl+EnEnTrAIt0RAS4Y0pW7Gfvv/xT4KegSkAcJY2WBUnIYVq+t2UjlA96Dse4idijMC+f4OK5K+S7wYgAXlakmew==
    providerClientSecret: AgBjvG9fza+hAMO6lLs+ii47ebP+y4Mgh0uLwAIsultF81Fdzh2KAahxDtI0Oz0JFUVUEpWUZZhhHT94mis3IjY78PqP/ror11yPGAjorxJoZDnc9St4Vn0MXGdjdbtye7Jz0FaMcj6eS4bHGIXtgWUiCYv/xN/dM57IKD9LlIXPH04GSKdK4bBNuhmQ88t8ekxM4jpv+44SMGmHUj8JUatJ7t+OkD+6Vg4mNzy0Ukj7yrHM165LFb12zBSubFdJbw5yeRM2N30RivSdGYi8EyhNMWN9jOW8hiHGysa5rgf+UOKPs/RF4qTNJetWA5/+3pBYQzDLRP7HfohV6eMZgpvR7oyubJ1X5fsK6ju6AU7tQNS4/CoAQNwk8G0wpFR+hwuZ91Kmo/8CzDfe1djb/NtawN5LIEwIdah8EADp5MsdRViagOnYVRQfaU3U+fWUFkJah41cJhm+CnPVRz3QX78bkWw2jHYM6cDe6DTBHAuIu8FWyYuQbfp2qVjyKGe1Alw39rKveVaKbqAs6bgfojeiiCIWQY9qzOXNAXmxCNw724av88ElKt8eQF2hfL9kytO+S3lbYZjeyvAVnuGW+znd423VGFlbzeta4UG3ukS8tCMou2okjek+uBqZk9EZrcTDZonlLb5l0ZSxso3ZZDpO3y2UvOhzKb8VwqhPzTEZg9Er5I+LRXuymYw7Pf46zwcO4LDaMrjhyQEowd9hsma37SqQHjM6UvDx512zuncobg==
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: longhorn-system,traefik,sudosos-test,loom
      name: oidc-auth
      namespace: shared-secrets
    type: Opaque
