apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  targetNamespace: traefik
  storageNamespace: traefik
  chart:
    spec:
      chart: traefik
      version: "39.0.8"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  interval: 1h
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    deployment:
      kind: DaemonSet
    service:
      spec:
        externalTrafficPolicy: Local
    ingressClass:
      enabled: true
      isDefaultClass: true
      name: traefik
    ports:
      web:
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
      websecure:
        asDefault: true
        forwardedHeaders:
          trustedIPs:
            - "10.82.50.107"
            - "145.116.44.122"
        transport:
          respondingTimeouts:
            readTimeout: 0
    logs:
      access:
        enabled: true
        format: "json"
        fields:
          headers:
            defaultmode: keep
    ingressRoute:
      dashboard:
        enabled: true
        entryPoints:
          - "websecure"
        matchRule: Host(`traefik.gewis.nl`)
        middlewares:
          - name: dashboard-auth
    providers:
      kubernetesIngress:
        allowExternalNameServices: true
      kubernetesCRD:
        allowExternalNameServices: true
      kubernetesGateway:
        enabled: true
    gateway:
      listeners:
        web:
          port: 8000
          protocol: HTTP
          namespacePolicy:
            from: All
        websecure:
          port: 8443
          protocol: HTTPS
          namespacePolicy:
            from: All
          certificateRefs:
            - name: wildcard-gewis-nl-tls
              namespace: traefik
    experimental:
      plugins:
        traefik-oidc-auth:
          moduleName: "github.com/sevensolutions/traefik-oidc-auth"
          version: "v0.18.0"
    tlsStore:
      default:
        defaultCertificate:
          secretName: wildcard-gewis-nl-tls
