---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc-secret
  namespace: traefik
spec:
  encryptedData:
    pluginSecret: AgBi3oTnsCYPuaRZLcBZG/d+Hz1hN1VW5JrQSWKoonczB/qh3x/CFcsaDsAdX/nV6fTZHqQNVGWXhDI/XH3s1ffyOfMHal+9snAu0ojmU/oIImgcgPYmsemLK9mxOBmgQsP3WO8L4jUp+ix/bIQHSjOX8FBKXQGsaKJzPkhM1+OQSkI8ntNsm5ddj8wUDud2gFO159CUQskxrnQrfjc5WW30cRIPxVYufdL6Nz6JIhM3pzSiDR0QkJrcY+q4ivJGkGo5z4vvCo6OPhs5jRxgriFcJuRsNglnwc7VghL3OgLsajI6qAoRkF3qr2zChSBu4YMyjgEtRpW7HRbUylbykZmiEk1zr0KQNI0nryQV5JeecwpNRrTLLxaai/kTVbbiPOk/c4JuBZFEY+kCxAF3nm7Ex4/ROT/seqYW1Ew2gwz1oR2ZT9TdZTsBgWwxkzHz9sI0Zv7SSLgS1tan99aDtO99oLBA0gKS56DklsjrsNIU09khdJwju5fJQwqsreCiV7qCrQOANxmQINljwqH48e4cTboduyaTR1KrBQ2Ik+O/xKhBISBkZCxumpwFmlr7r4SfAEr4qgzpWxrmWo9AVUKJWtSGdqTecSpejp/8Fhy49cgaxp2OkN9r4GdRp3if4WAsPK+1tmStuxWrBzHSGxqLVD4zzKHgMZYUQGJIRJTc2jVYOL3QUqAs9sOI5xoG1d/GlRgGwMsdPyGEbABj+8xZLYBjM90etld3C58zDsMdBg==
    providerClientSecret: AgBajqXf2NNE8IKlQiahzz8SIjrDRjntyH1EDNjWZorW8s8Kq4XDMguudSiXqumqBiG7KE/KutBwyBUyZBUbvFThuC0plUF++y0BsbPwh6sqqeJtY6x8U/e4/MkRUQyAl8h/d12lFAGtKVMzXhSAjBKl3oOF1yhLbKNg+4l65Zgm4BYg3pbXAYSHOumfNKLzZ3Q+fZJwQiaR6fCMmAaOMee4OpTNYIP6lNoE2yhO4KD1yrdQdLgmR6yA2L+JXIcIIwJVdBvWYJboekz0vESN01l7+NZtgCA3Kgq0Bzc5Am5/LMmv4Zn3BABH0B3XHOVqDvevtbJxRTmDnydTpe5yTYdX0fxN2ydNQdDhd4snrHTFmJ6C2KHeAcgHuGx9k6Wacsnwoj1A3k1jWnq6BOqz5ZzrcYpNWTEa0OnK+wcxZR2AwaNwERNpQFmLeF7ADsQ9zGvJyUm9qajk7nQGcbSCN/4JM0kTzyKl+pIk/kG2bUwFOAf+AhVAvchejlzSqvJxTvUY3L1jTcGrb4I9rORClG7awjyagzdPi3E7sr8J8RQqf/tJ5bMSW2mcMbsq8mnGxYiKK5y/hy04Bf+hpZAMjPiMw7jlyvQdJuQ032Bnxsi3sezH6hT+6rbBezxkQIm1vjJgi3Jw0liSNDsLL11x5eFWEP+q+455KIhX54FZ9Okr1GCFsBHIUZbGOfz+v4OTdx8VNGDtAGd6Azar6r6t36SHAwEtuTMRHvaqbRDsJFC4lA==
  template:
    metadata:
      name: oidc-secret
      namespace: traefik
    type: Opaque
