---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc-secret
  namespace: traefik
spec:
  encryptedData:
    pluginSecret: AgB27F6RuxbazI0wKdyIkub+AQKYJK2bSaO9F2zSzKhTn7tCHtW/OK4MyUrKSkKkwxCHNUOKq62PVEu+38+Tf9x6IUTyqtl+fTfzQ9xdBNQ2HVv/jK8CgPAfigj/OlkOMXHldB42F5l3ITWLzi/qjodVfZiSyk+7Th5G5aWggxuiCaW87vAonHBCeYtUvkVHSzDp3t+rWs1YsRwfCDunddSHp5T0by4yXXIXCBZL/MiZquryVY00qHAR3ZBpAxLVCHKcUKskj7UPqGcf4vky/Ju+C0ia9CR1/Vpmo5OwvhGbAkXmJlS/SQPV2SYNTH7344AF3mo0vvSeQ6WgSMVn0YVugs5YVWyuiE17YkvvGkx5Hu3i8k7iMPMe+Hycwcsy/p2ylWOsZ/7CZ7vPmVI2c/yOV1mZuvll3LZymj/JZLPVFzR1TJmIDfMwkxV3b3/y69+bN4Dxc6FMPNCCCBcgOyg6tkjobPfU5SklRF7AUJuY3ZgwWe1DfCq8afQMZq98qCgyJbTXc99ONn4boOIeFAR3uiM2n3WJY9qrp5fXTSQBRx1aGxtfR75e5PeZHYh1UuOCHh4FPnW1Ovi97ne/11eZiatgDv/cPZ6zElVcEwfmWO4BFwSMMwS9UPjKRUHdPKZgJICGk3z2R8qwREAhTC3z3JRLhKCYKRhCZW9vtmRNbix4HOgvAFn5zutEqry4hA6Vz7TXJ2vIuYPdgthnjTAbeNTLcbxAINWa9KXYA7AECA==
    providerClientSecret: AgC36MmSEb1gxMhSL8+vydXK9QGxFnquZ3qAXubQE4PefNgyrR7we8w6xqW5K+WLPP5rhcSlGomltUInNlcQ9uGlUYMrPK+PbNgTw84f9SGSSu1ea5ZvHoiZR2lemscidRSTOhnq5XwOP55E/L7QCE28CJ/QQ8cwUGwFo6vJMP18Q+CKzEzoLyHfIkhptPvIy7zozMViojAVCxir71CsI//Tw5GTLLAIxK4Kut/5mtJcl9yfXzETPyP2V6oRs655I9JtQc3uTf5JCPVP+ODReFFIETGS/kPchbxwCjp3vYthMqoHrUAiwX7GobjUnl7r6m71I0oXKwO20clOczko8pZ2WcCq/bqeDQ4O8GlI/T3EbeNRQHtVc3UnctHABeaB+K5SiwXVSpA8G39uphFlbGosVjl6f1h6d89o3jqynSEs59NkikzaJ7aMo3WeICIloBJ+umCrhEUC4zwNHpVSD7jJoj/tEn9h9Uq2sdWiNvJBxpM9OsOOO1cSgD7RkFVUpcLrYEUd+r+9tIXIft6E8g/PvYUC2kZS8JqnWUK3KlTDlgT+nlk2ixr0uvmXgaGd/6nMaJhhUWUY6aa2AyGbjBchXkaxS68fGp0Rzkffmh0y17yrEhpncQCdzjDef/u6qXH3x8HDcvJStY/buHoP88xCJUhXm3LoN5vD6oE4NsYeHiDt5+zDznJa2dm+etfFprgPTkHlUiZo1fiSWXJqGLxoZxWlXR+gCNdgSfSW59jx7g==
  template:
    metadata:
      name: oidc-secret
      namespace: traefik
    type: Opaque
