---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbird-mgmt-api-key
  namespace: netbird
spec:
  encryptedData:
    NB_API_KEY: AgCv00JMbv8lBqpbEouaYAVEMfS5+jC/uN3lzWBiK3b+Cl0V/xzVelftklgfn8+bhR7n+ZkTL62nv/C5nyGfjDMPelsueFHDt+WVPQZDtU71/Kso2DayC9wg1/ztkMzeFq1a/dqfT8Lh//MupxnAG8+3wyebt96yoPV7dKLjfJE+juQHnTV5MzpISVzs8IUbImSiOMNllvTwB7sXsTCZgHdyf9FdVnBPMAg4GFzzPGXqYGemvJCNj7dIcv1zw54AAqGgfVY0u8yHg2ZubG65qRMODUi96Y0VIeRnlV3DuUBN+JP14UCfN40xtYrA1oQ9nkWY29OWVttODWzTBwhYLNRL7XKW6OIs4w3OOKlFclDH9EnB/y8ZkS2XvC7PUqGgm5Pq8Xrxtf9r+p3AZ4o/e6qj65sjKpL/z19JzMfa9JZ1rg3L13stCr3seay4F+Mcu1hLdFsONvX1YDIVHBtyNBcohHlj3TCgPrnXi4QNwikBsHieND3Fl+oOByCM5wz3CTseZMi4YMJMIWwTq0bbDi49kq5qofr7pIYUe7mCIsuBvNZ5zmBaXqpCcumSr6SdFEwpudJ6Nnso2wkUs6rD4GH9s406lxyErNih7fWOYufVg2Sv5uJZIZl3SI3RUGKtlv8PLOQ9zBo47UqMg4oBiZ/WaGPFsT2kSenp+em8L6BkC0raZvB+hZ4lu61uDtzh/Cm8wBjlA3S/Yja9y55g9AaXVTr9Urcu/29Gf72Roma75j+b1Wrg69lH
  template:
    metadata:
      name: netbird-mgmt-api-key
      namespace: netbird
    type: Opaque
