apiVersion: v1
kind: ServiceAccount
metadata:
  name: clusterproxy-gewis-prod
  namespace: netbird
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterproxy-gewis-prod
rules:
  - apiGroups: [""]
    resources: ["users", "groups"]
    verbs: ["impersonate"]
  - apiGroups: ["authentication.k8s.io"]
    resources: ["userextras/*", "uids"]
    verbs: ["impersonate"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterproxy-gewis-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterproxy-gewis-prod
subjects:
  - kind: ServiceAccount
    name: clusterproxy-gewis-prod
    namespace: netbird
---
apiVersion: netbird.io/v1alpha1
kind: ClusterProxy
metadata:
  name: gewis-prod
  namespace: netbird
spec:
  clusterName: gewis-prod
  serviceAccountName: clusterproxy-gewis-prod
  groups:
    - name: "k8s-api"
