---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbird-reverse-proxy-token
  namespace: netbird
spec:
  encryptedData:
    NB_PROXY_TOKEN: AgCKq75BjqKBZPRpu8RvrVMJzMlX+/3JWjNvnD/FwoPjS1Z4MW9U+/N88uuUiId9kruJqXyQfHfXv0dqtSS8g47Uez/ho4jM6nRS5PVpzru+QQjuDB7NMNBPshEVrXaS+MnmgAQYD4MsKIMOmsDmrkry+x3cF7r1N5OsVZ6sVKtyhtd4nfkrpszqiWO5RXYM5Cj2zAZyqWblnNHPe6TEV6ePHPmPAgcib+0yRetYzYMtW1BrFb2eU52Io9eGylkOLz4P0uQmMhUVup/gbyR5kA5ZXvjSsn52TpfKtuVUqLMyyLShgECQMJSiXMetwI/k/4J5jbVxH7aN40YeR56aw6GVK10SS4zfWReGSOKCWzDZfkJBSnlreazlOQCe/7fOqH4Znv/rwanPtKSTeIz1O6ehfJBSo8+LGkIbylttFiwkKRcLWvn+gUQ1GHByhMaB+ClcU8aRNCOgmlrPNdbbE2yEa0/FfqUKdKet7UlpSkH2Il59TIeicXZYrf3wQvoZ1vML1QZpfq4EuggMymSrfzgux49UQcjAmvheV5kHIu0RbuGACsuik/0h5SKmTQew2TOW1NsiyF1CoXziUqEItZi3A1uooguCzkWNdoqTRZ7wvs0Y6LISJ0LCBB9npioR65vrquG/7M3gyJlUVn+/jMSmVuQSzUHcJjaYjBXkFodwAG8V2IYOUldacX9JGaTIlUvX6GVNt/jZf/k2XNigDaqSFN62cGONG3fIJ01tnl5sNuN8iF9EJ2PS
  template:
    metadata:
      name: netbird-reverse-proxy-token
      namespace: netbird
    type: Opaque
