---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbird-config
  namespace: netbird
spec:
  encryptedData:
    config.yaml: AgC8wmNqrm4bMdZuuMSWNijsATKxFKNkvFzzz/fDdqhdjJ3PjQ1AP3t8gQGE8MxlkQSV9QMT4tDaMcFBzxkZf3GjOkalUDzacD2wK1xGnwTNJgmKE3P1FWKrh0PvUnehpTInVe6tpskui4vPtsVuBNWAaiV/BfWojRmCE5cSccf/DUoHbnkydCmbDxj1hCQx9zAxj4fcXtSdd1ZJ9MYahPd3VBYaGMF+ODZZ2XghMaYQqUaD4Qr9q3P51CKiGHZ0SICNEg7aCVN9N6B1IHjHvbhWTfnXkjmBRsCUZxjIQXuSw30JCTn5zEq+PjTp0yz/oeg/xfbSlTvQPHCJ1F6xIf7r1p4u8J7FUyERBE1ypA0gy2q4P63iHJK4SRDnIKg6/xgG+C1UJDCHgVWENjb8dQIEJDRF60f6anxnfTVCwNMR3Fkb3zE8YKkAU+sUI4bR+j8N2V/2Y0CSz8U4R74cVSi0pvU5AJ8kRuS8NNCfv4YAtn/gtrTADNGzzl8+iLH3JCt07efyiKeTUMBa31sZ7N0ZhMKhoSH1+561ptqMCFAcwrY1mXokL9JnUSgifAvgmVrnR08zZtu1UkfZVMBT57Ia95/lWRNhbQe1hKLhINq74ODL1i5TkdKFS9AjiHwtatzhlSVcNIUVqouVtzHz5NrNTpYDDjS1l5W/L2X04g5t/+qCxD7KK5Wwwf57hLG6jSpjNKNuAXNd/emIxZrY9IKK8Wk6SPskykq+PJxUqDkt6NKs11D2U4c2X2GaxsUUpCHSCZ+Maoty0mEPJ5H+s0fThu0hK4bu2di6NIfjDY/n7XtTd3eEjHTPxoH0tFWd0Rh1WRh9FUsE0xmKX9bl6ZnDs8Q6sWOmtCl1Yudg50OoVxjglQ5W1hEkERjEi8Rvny7SF/ZqyQbhSVC6Yy7z7DF2zxoVclvlAzXfTGG/iEf1gMPEcKiHwcuM9tTCCao8YD94Cfbn/tBUQVPZUaJsFg5aEh9UAuaNR6ZoGP9zmwOQoJ61YpGXOPrWbwqa5vI/cmjOHjgP+Ce9kY7SUiGbHHeuIO5smIduAjU9uVmnMa2VRbUH/jgdvRZAm2wb4VtsM/G1xDLD4nSSFoWC9nLG5z70o4pCr5ZoYBhwhywZDqFTWZ7ndL1cajtZXARgx+b4vwajx+Z3VaQkyoiZHa1Wj3tyF3KippR4QOkp2kpgcjWKDQV++4p3zUmjljwfmp6enyY2qDkC2poJrPx1MU1B5UuliTO3KVBWbEibyqHMwQYgF69qq9lvVcUr08BZrUr2BBAyGeIcTN4HOo5fO97Yg5395XnlRjIRe0qZeD+OTG3XJkYyc6nx72+6QhGOJt/jqWJIkO/9xz2TOS+/oGvYoK9z3Bqh++9bdihkvz20ckvjqOuqOztbOrwapqSm/L7M1rbP3WmC0BUjXZW9XhWV3lBv7syANtvuWvDtzwD+Ke6CQHLhJO066KGtyT1ir0q57er+2nj8b/65HDiUZPdr/dXas0x3fhBO/176h6+FEnhea4l9oYg3uAeM0etT+ZsT899/zhNmxueWa+Yl9Zalj/GbWODdDxBp+h9jZZ3xjqg6+iZP6L4jWzb04FEERo19NLbWHC5Ejha8tH8fTGybqoSCJ91e
  template:
    metadata:
      name: netbird-config
      namespace: netbird
    type: Opaque
---
# apiVersion: v1
# kind: Secret
# metadata:
#     name: netbird-config
#     namespace: netbird
# type: Opaque
# stringData:
#     config.yaml: |-
#         server:
#           listenAddress: ":80"
#           exposedAddress: "https://nb.gewis.nl:443"
#           stunPorts:
#             - 3478
#           metricsPort: 9090
#           healthcheckAddress: ":9000"
#           logLevel: "info"
#           logFile: "console"
#
#           authSecret: "<authSecret>"
#           dataDir: "/var/lib/netbird"
#
#           auth:
#             issuer: "https://nb.gewis.nl/oauth2"
#             signKeyRefreshEnabled: true
#             dashboardRedirectURIs:
#               - "https://nb.gewis.nl/nb-auth"
#               - "https://nb.gewis.nl/nb-silent-auth"
#             cliRedirectURIs:
#               - "http://localhost:53000/"
#
#           reverseProxy:
#             trustedHTTPProxies:
#               - "172.30.0.10/32"
#
#           store:
#             engine: "sqlite"
#             encryptionKey: "<encryptionKey>"